{% set name = "pycrystal" %}
{% set version = "1.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycrystal-{{ version }}.tar.gz
  sha256: 5328c82dca0ccb769f67605ae7bca8bff2c9d841eff69a7e8c2ea70063a73487
  patches:
    - bs4.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ase
    - pyparsing
    - requests
    - bs4

test:
  imports:
    - pycrystal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tilde-lab/pycrystal
  summary: Utilities for ab initio modeling suite CRYSTAL
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
